GET http://localhost:3000/users?&page=1&limit=50
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjQsImVtYWlsIjoidG9kMUBnbWFpbC5jb20iLCJpYXQiOjE3NzE3NzU0NTUsImV4cCI6MTc3MTc3OTA1NSwiYXVkIjoibG9jYWxob3N0OjMwMDAiLCJpc3MiOiJsb2NhbGhvc3QifQ.90P27i8YO3SlCz_KqsmF7gYitvzn3IhOd7T8txXSJ3A
